### ISSUE TITLE
Multi moveto bug: Complex shapes

### ISSUE THREAD

**Issue by dalisoft** [colinmeinke/svg-points#10]
I dont know about this bug more, but enough for show to you what i mean.

WildernessJS: http://codepen.io/dalisoft/pen/egdPZX

**Comment by colinmeinke** [comment]
what do you think is a bug?

**Comment by dalisoft** [comment]
you see triangulation?

**Comment by colinmeinke** [comment]
I am closing this, as this library has nothing to do with moveTo. I assume you want to file a bug with the wilderness library. If so please produce a proper bug report, clear explanation of the bug and the minimum viable code to reproduce. Bear in mind I have not rolled out the latest versions of points and svg-points to Wilderness yet.

**Comment by dalisoft** [comment]
Hey, just a wait. You see i passed value as `SVG-points` and `points`
