### ISSUE TITLE
ES6 import not works for other module made by me

### ISSUE THREAD

**Issue by dalisoft** [colinmeinke/svg-points#12]
Hi @colinmeinke.
I have issue with `imports` for my modules. I am using for `svg-points` imports and works best, but for my modules not. There some configs?

Require (nodejs require) works for both module.

I am too configured like your, but not works.

**Comment by colinmeinke** [comment]
I don't understand your issue. Can you give me a minimal code example?

**Comment by dalisoft** [comment]
Es6 import works for svgpoints. Its good, as dependecy of my module. But my module not imports with es6, fails as my module dependent to my other module. I asking help, this is not svgpoints issue. Thanks for reply

**Comment by colinmeinke** [comment]
@dalisoft can you show me some code?

**Comment by dalisoft** [comment]
Look at tez (tez.js on npm) repo. I am trying to make like that but nothing gets done. Thanks for reply
